- name: breaking
  color: "d73a4a"
  description: "Changes that break backward compatibility"

- name: feature
  color: "a2eeef"
  description: "New features"

- name: enhancement
  color: "0e8a16"
  description: "Improvements to existing features"

- name: bug
  color: "d73a4a"
  description: "Bug fixes"

- name: security
  color: "ee0701"
  description: "Security-related updates"

- name: chore
  color: "fbca04"
  description: "Maintenance tasks"

- name: maintenance
  color: "fef2c0"
  description: "General upkeep and refactoring"

- name: docs
  color: "0075ca"
  description: "Documentation improvements"

- name: documentation
  color: "cfd3d7"
  description: "Additional documentation-related updates"

- name: dependencies
  color: "0366d6"
  description: "Dependency updates"
