# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  lint:
    desc: Runs GolangCI-Lint
    cmds:
      - golangci-lint run ./... --fix
    silent: true

  test:
    desc: Runs tests with coverage
    cmds:
      - gotestsum --format=testname -- ./... -coverprofile=coverage.out
    silent: true

  godoc:
    desc: Generate documentation for Golang packages
    cmds:
      - gomarkdoc --output GODOC.md ./
      - gomarkdoc --output '{{ "{{" }}.Dir}}/README.md' ./checks/...

  docs-serve:
    desc: Serve documentation locally
    cmds:
      - mkdocs serve
    silent: true
