name: Build Docs
on:
  push:
    branches:
      - main
      - master
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/docs.yml
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-docs-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material

      - name: Build documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --clean
