name: PR Check
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1 # 1.5.2
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: "false"

  validate-pr-labels:
    name: Check PR Labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:v1.6.113@sha256:ce17e51c4d4e6e33cdf91b8e6882325d715c2a75fa96a6db9047a63599e79b0a
        with:
          one_of: "breaking,feature,enhancement,bug,docs,dependencies,security,ci,maintenance,chore"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
